<?php

namespace App\Http\Requests\Api\V1\User;

use Illuminate\Foundation\Http\FormRequest;

/**
 * @OA\Schema(
 *     type="object",
 *     title="Request for create or update agreement",
 *     required={"id"}
 * )
 */
class CarHistoryRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {

        return [
            'id'  => ['required', 'string'],
            'invoices'  => ['nullable', 'array'],
            'invoices.*.id'  => ['nullable', 'string'],
            'invoices.*.address'  => ['nullable', 'string'],
            'invoices.*.amountIncludingVAT'  => ['nullable'],
            'invoices.*.amountVAT'  => ['nullable'],
            'invoices.*.amountWithoutVAT'  => ['nullable'],
            'invoices.*.author'  => ['nullable', 'string'],
            'invoices.*.contactInformation'  => ['nullable'],
            'invoices.*.date'  => ['nullable'],
            'invoices.*.discount'  => ['nullable'],
            'invoices.*.etc'  => ['nullable'],
            'invoices.*.number'  => ['nullable'],
            'invoices.*.organization'  => ['nullable'],
            'invoices.*.phone'  => ['nullable'],
            'invoices.*.shopper'  => ['nullable'],
            'invoices.*.taxCode'  => ['nullable'],
            'invoices.*.parts'  => ['nullable', 'array'],
            'invoices.*.parts.*.name'  => ['nullable'],
            'invoices.*.parts.*.ref'  => ['nullable'],
            'invoices.*.parts.*.unit'  => ['nullable'],
            'invoices.*.parts.*.discountedPrice'  => ['nullable'],
            'invoices.*.parts.*.price'  => ['nullable'],
            'invoices.*.parts.*.quantity'  => ['nullable'],
            'invoices.*.parts.*.rate'  => ['nullable'],
            'invoices.*.parts.*.sum'  => ['nullable'],
            'orders'  => ['nullable', 'array'],
            'orders.*.AmountInWords'  => ['nullable'],
            'orders.*.AmountIncludingVAT'  => ['nullable'],
            'orders.*.AmountWithoutVAT'  => ['nullable'],
            'orders.*.AmountVAT'  => ['nullable'],
            'orders.*.bodyNumber'  => ['nullable'],
            'orders.*.closingDate'  => ['nullable'],
            'orders.*.currentAccount'  => ['nullable'],
            'orders.*.date'  => ['nullable'],
            'orders.*.dateOfSale'  => ['nullable'],
            'orders.*.dealer'  => ['nullable'],
            'orders.*.disassembledParts'  => ['nullable'],
            'orders.*.discount'  => ['nullable'],
            'orders.*.discountJobs'  => ['nullable'],
            'orders.*.discountParts'  => ['nullable'],
            'orders.*.id'  => ['nullable'],
            'orders.*.jobsAmountIncludingVAT'  => ['nullable'],
            'orders.*.jobsAmountVAT'  => ['nullable'],
            'orders.*.jobsAmountWithoutVAT'  => ['nullable'],
            'orders.*.model'  => ['nullable'],
            'orders.*.number'  => ['nullable'],
            'orders.*.partsAmountIncludingVAT'  => ['nullable'],
            'orders.*.partsAmountVAT'  => ['nullable'],
            'orders.*.partsAmountWithoutVAT'  => ['nullable'],
            'orders.*.producer'  => ['nullable'],
            'orders.*.recommendations'  => ['nullable'],
            'orders.*.repairType'  => ['nullable'],
            'orders.*.stateNumber'  => ['nullable'],
            'orders.*.mileage'  => ['nullable'],
            'orders.*.parts'  => ['nullable', 'array'],
            'orders.*.parts.*.name'  => ['nullable'],
            'orders.*.parts.*.amountIncludingVAT'  => ['nullable'],
            'orders.*.parts.*.amountWithoutVAT'  => ['nullable'],
            'orders.*.parts.*.price'  => ['nullable'],
            'orders.*.parts.*.priceWithVAT'  => ['nullable'],
            'orders.*.parts.*.priceWithoutVAT'  => ['nullable'],
            'orders.*.parts.*.producer'  => ['nullable'],
            'orders.*.parts.*.quantity'  => ['nullable'],
            'orders.*.parts.*.unit'  => ['nullable'],
            'orders.*.parts.*.ref'  => ['nullable'],
            'orders.*.parts.*.rate'  => ['nullable'],
            'orders.*.jobs'  => ['nullable', 'array'],
            'orders.*.jobs.*.name'  => ['nullable'],
            'orders.*.jobs.*.amountIncludingVAT'  => ['nullable'],
            'orders.*.jobs.*.amountWithoutVAT'  => ['nullable'],
            'orders.*.jobs.*.price'  => ['nullable'],
            'orders.*.jobs.*.priceWithVAT'  => ['nullable'],
            'orders.*.jobs.*.priceWithoutVAT'  => ['nullable'],
            'orders.*.jobs.*.ref'  => ['nullable'],
            'orders.*.jobs.*.rate'  => ['nullable'],
            'orders.customer'  => ['nullable', 'array'],
            'orders.customer.FIO'  => ['nullable', 'string'],
            'orders.customer.date'  => ['nullable'],
            'orders.customer.email'  => ['nullable'],
            'orders.customer.name'  => ['nullable'],
            'orders.customer.number'  => ['nullable'],
            'orders.customer.phone'  => ['nullable'],
            'orders.dispatcher'  => ['nullable', 'array'],
            'orders.dispatcher.FIO'  => ['nullable'],
            'orders.dispatcher.date'  => ['nullable'],
            'orders.dispatcher.name'  => ['nullable'],
            'orders.dispatcher.number'  => ['nullable'],
            'orders.dispatcher.position'  => ['nullable'],
            'orders.organization'  => ['nullable', 'array'],
            'orders.organization.address'  => ['nullable'],
            'orders.organization.phone'  => ['nullable'],
            'orders.organization.name'  => ['nullable'],
            'orders.owner'  => ['nullable', 'array'],
            'orders.owner.address'  => ['nullable', 'string'],
            'orders.owner.email'  => ['nullable'],
            'orders.owner.name'  => ['nullable'],
            'orders.owner.certificate'  => ['nullable'],
            'orders.owner.phone'  => ['nullable'],
            'orders.owner.etc'  => ['nullable'],
            'orders.payer'  => ['nullable', 'array'],
            'orders.payer.name'  => ['nullable'],
            'orders.payer.date'  => ['nullable'],
            'orders.payer.number'  => ['nullable'],
            'orders.payer.contract'  => ['nullable'],
        ];

//        return [
//            'id'  => ['required', 'string'],
//            'invoices'  => ['nullable', 'array'],
//            'invoices.*.id'  => ['nullable', 'string'],
//            'invoices.*.address'  => ['nullable', 'string'],
//            'invoices.*.amountIncludingVAT'  => ['nullable', 'string'],
//            'invoices.*.amountVAT'  => ['nullable', 'string'],
//            'invoices.*.amountWithoutVAT'  => ['nullable', 'string'],
//            'invoices.*.author'  => ['nullable', 'string'],
//            'invoices.*.contactInformation'  => ['nullable', 'string'],
//            'invoices.*.date'  => ['nullable', 'string'],
//            'invoices.*.discount'  => ['nullable', 'string'],
//            'invoices.*.etc'  => ['nullable', 'string'],
//            'invoices.*.number'  => ['nullable', 'string'],
//            'invoices.*.organization'  => ['nullable', 'string'],
//            'invoices.*.phone'  => ['nullable', 'string'],
//            'invoices.*.shopper'  => ['nullable', 'string'],
//            'invoices.*.taxCode'  => ['nullable', 'string'],
//            'invoices.*.parts'  => ['nullable', 'array'],
//            'invoices.*.parts.*.name'  => ['nullable', 'string'],
//            'invoices.*.parts.*.ref'  => ['nullable', 'string'],
//            'invoices.*.parts.*.unit'  => ['nullable', 'string'],
//            'invoices.*.parts.*.discountedPrice'  => ['nullable', 'string'],
//            'invoices.*.parts.*.price'  => ['nullable', 'string'],
//            'invoices.*.parts.*.quantity'  => ['nullable', 'string'],
//            'invoices.*.parts.*.rate'  => ['nullable', 'string'],
//            'invoices.*.parts.*.sum'  => ['nullable', 'string'],
//            'orders'  => ['nullable', 'array'],
//            'orders.*.AmountInWords'  => ['nullable', 'string'],
//            'orders.*.AmountIncludingVAT'  => ['nullable', 'string'],
//            'orders.*.AmountWithoutVAT'  => ['nullable', 'string'],
//            'orders.*.AmountVAT'  => ['nullable', 'string'],
//            'orders.*.bodyNumber'  => ['nullable', 'string'],
//            'orders.*.closingDate'  => ['nullable', 'string'],
//            'orders.*.currentAccount'  => ['nullable', 'string'],
//            'orders.*.date'  => ['nullable', 'string'],
//            'orders.*.dateOfSale'  => ['nullable', 'string'],
//            'orders.*.dealer'  => ['nullable', 'string'],
//            'orders.*.disassembledParts'  => ['nullable', 'string'],
//            'orders.*.discount'  => ['nullable', 'string'],
//            'orders.*.discountJobs'  => ['nullable', 'string'],
//            'orders.*.discountParts'  => ['nullable', 'string'],
//            'orders.*.id'  => ['nullable', 'string'],
//            'orders.*.jobsAmountIncludingVAT'  => ['nullable', 'string'],
//            'orders.*.jobsAmountVAT'  => ['nullable', 'string'],
//            'orders.*.jobsAmountWithoutVAT'  => ['nullable', 'string'],
//            'orders.*.model'  => ['nullable', 'string'],
//            'orders.*.number'  => ['nullable', 'string'],
//            'orders.*.partsAmountIncludingVAT'  => ['nullable', 'string'],
//            'orders.*.partsAmountVAT'  => ['nullable', 'string'],
//            'orders.*.partsAmountWithoutVAT'  => ['nullable', 'string'],
//            'orders.*.producer'  => ['nullable', 'string'],
//            'orders.*.recommendations'  => ['nullable', 'string'],
//            'orders.*.repairType'  => ['nullable', 'string'],
//            'orders.*.stateNumber'  => ['nullable', 'string'],
//            'orders.*.mileage'  => ['nullable', 'string'],
//            'orders.*.parts'  => ['nullable', 'array'],
//            'orders.*.parts.*.name'  => ['nullable', 'string'],
//            'orders.*.parts.*.amountIncludingVAT'  => ['nullable', 'string'],
//            'orders.*.parts.*.amountWithoutVAT'  => ['nullable', 'string'],
//            'orders.*.parts.*.price'  => ['nullable', 'string'],
//            'orders.*.parts.*.priceWithVAT'  => ['nullable', 'string'],
//            'orders.*.parts.*.priceWithoutVAT'  => ['nullable', 'string'],
//            'orders.*.parts.*.producer'  => ['nullable', 'string'],
//            'orders.*.parts.*.quantity'  => ['nullable', 'string'],
//            'orders.*.parts.*.unit'  => ['nullable', 'string'],
//            'orders.*.parts.*.ref'  => ['nullable', 'string'],
//            'orders.*.parts.*.rate'  => ['nullable', 'string'],
//            'orders.*.jobs'  => ['nullable', 'array'],
//            'orders.*.jobs.*.name'  => ['nullable', 'string'],
//            'orders.*.jobs.*.amountIncludingVAT'  => ['nullable', 'string'],
//            'orders.*.jobs.*.amountWithoutVAT'  => ['nullable', 'string'],
//            'orders.*.jobs.*.price'  => ['nullable', 'string'],
//            'orders.*.jobs.*.priceWithVAT'  => ['nullable', 'string'],
//            'orders.*.jobs.*.priceWithoutVAT'  => ['nullable', 'string'],
//            'orders.*.jobs.*.ref'  => ['nullable', 'string'],
//            'orders.*.jobs.*.rate'  => ['nullable', 'string'],
//            'orders.customer'  => ['nullable', 'array'],
//            'orders.customer.FIO'  => ['nullable', 'string'],
//            'orders.customer.date'  => ['nullable', 'string'],
//            'orders.customer.email'  => ['nullable', 'string'],
//            'orders.customer.name'  => ['nullable', 'string'],
//            'orders.customer.number'  => ['nullable', 'string'],
//            'orders.customer.phone'  => ['nullable', 'string'],
//            'orders.dispatcher'  => ['nullable', 'array'],
//            'orders.dispatcher.FIO'  => ['nullable', 'string'],
//            'orders.dispatcher.date'  => ['nullable', 'string'],
//            'orders.dispatcher.name'  => ['nullable', 'string'],
//            'orders.dispatcher.number'  => ['nullable', 'string'],
//            'orders.dispatcher.position'  => ['nullable', 'string'],
//            'orders.organization'  => ['nullable', 'array'],
//            'orders.organization.address'  => ['nullable', 'string'],
//            'orders.organization.phone'  => ['nullable', 'string'],
//            'orders.organization.name'  => ['nullable', 'string'],
//            'orders.owner'  => ['nullable', 'array'],
//            'orders.owner.address'  => ['nullable', 'string'],
//            'orders.owner.email'  => ['nullable', 'string'],
//            'orders.owner.name'  => ['nullable', 'string'],
//            'orders.owner.certificate'  => ['nullable', 'string'],
//            'orders.owner.phone'  => ['nullable', 'string'],
//            'orders.owner.etc'  => ['nullable', 'string'],
//            'orders.payer'  => ['nullable', 'array'],
//            'orders.payer.name'  => ['nullable', 'string'],
//            'orders.payer.date'  => ['nullable', 'string'],
//            'orders.payer.number'  => ['nullable', 'string'],
//            'orders.payer.contract'  => ['nullable', 'string'],
//        ];

        /**
         * @OA\Property(property="id", title="UUID", description="UUID автомобиля", example="10266ab2-7cec-11ec-8277-4cd98fc26f14"),
         * @OA\Property(property="invoices", title="invoices", description="масив рахунків", type="array",  @OA\Items(
         *      @OA\Property(property="address", title="address", description="адрес", example="м. Київ, вул. Мілютенка, будинок №26, кв. 56"),
         *      @OA\Property(property="amountIncludingVAT", title="amountIncludingVAT", description="сума з ПДВ", example="3 122,76"),
         *      @OA\Property(property="amountVAT", title="amountVAT", description="сума ПДВ", example="520,46"),
         *      @OA\Property(property="amountWithoutVAT", title="amountWithoutVAT", description="сума без ПДВ", example="2 602,3"),
         *      @OA\Property(property="author", title="author", description="автор", example="Білан Олександр Анатолійович"),
         *      @OA\Property(property="contactInformation", title="contactInformation", description="контактна інформація", example="07400, Україна, Київська область, місто Бровари, вулиця Старотроїцька, будинок №42 Тел. (044) 4902300, Факс р/с UA183005280000026001455022593 (Гривна) в ПАТ «ОТП Банк», МФО:300528 код ЄДРПОУ 34356004"),
         *      @OA\Property(property="date", title="date", description="дата", example="10.07.2018"),
         *      @OA\Property(property="discount", title="discount", description="знижка", example="459,22"),
         *      @OA\Property(property="etc", title="etc", description="Інше", example="Отсутствует"),
         *      @OA\Property(property="id", title="id", description="ідентифікатор елементу історії", example="Пикассо_8cfc05bd-844c-11e8-a705-005056812a5f"),
         *      @OA\Property(property="number", title="number", description="номер", example="VSK0032586"),
         *      @OA\Property(property="organization", title="organization", description="організація", example="ТОВ Арма Моторс"),
         *      @OA\Property(property="phone", title="phone", description="номер телефону", example="(098) 2394697"),
         *      @OA\Property(property="shopper", title="shopper", description="покупець", example="Пономаренко Людмила Іванівна"),
         *      @OA\Property(property="taxCode", title="taxCode", description="податковий код", example="ax344s3"),
         *      @OA\Property(property="parts", title="Parts", type="array",  @OA\Items(
         *          @OA\Property(property="name", title="Name", description="назва товару", example="Олива Elf Evolution Full-Tech FE 5W30 208L"),
         *          @OA\Property(property="ref", title="ref", description="каложний номер товару", example="000434"),
         *          @OA\Property(property="unit", title="unit", description="одиниця виміру", example="л"),
         *          @OA\Property(property="discountedPrice", title="discountedPrice", description="ціна зі знидкою", example="174,96"),
         *          @OA\Property(property="price", title="price", description="ціна", example="205,83"),
         *          @OA\Property(property="quantity", title="quantity", description="кількість", example="3,5"),
         *          @OA\Property(property="rate", title="rate", description="відсоток знижки", example="15"),
         *          @OA\Property(property="sum", title="sum", description="сума", example="612,36"),
         *      ))
         * ))
         * @OA\Property(property="orders", title="orders", description="масив актів", type="array",  @OA\Items(
         *      @OA\Property(property="AmountInWords", title="AmountInWords", description="сума прописом", example="Три тисячі сто двадцять дві гривні сімдесят шість копійок"),
         *      @OA\Property(property="AmountIncludingVAT", title="AmountIncludingVAT", description="сума з ПДВ", example="3122,76"),
         *      @OA\Property(property="AmountWithoutVAT", title="AmountWithoutVAT", description="сума без ПДВ", example="2602,30"),
         *      @OA\Property(property="AmountVAT", title="AmountVAT", description="сума ПДВ", example="2520,46"),
         *      @OA\Property(property="bodyNumber", title="bodyNumber", description="номер кузова", example="VF3WAKFT0CE036346"),
         *      @OA\Property(property="closingDate", title="closingDate", description="дата закриття", example="01.12.2012"),
         *      @OA\Property(property="currentAccount", title="currentAccount", description="рахунок", example="Р/р UA183005280000026001455022593 в АТ ОТП Банк в м. МФО 300528 код ЄДРПОУ 34356004"),
         *      @OA\Property(property="date", title="date", description="дата", example="10 липня 2018 р."),
         *      @OA\Property(property="dateOfSale", title="dateOfSale", description="дата продажі", example="01.12.2012"),
         *      @OA\Property(property="dealer", title="dealer", description="дилер", example="Офіційний дилер в Україні"),
         *      @OA\Property(property="disassembledParts", title="disassembledParts", description="сума без ПДВ", example="10.07.2018"),
         *      @OA\Property(property="discount", title="discount", description="знижка", example="551,08"),
         *      @OA\Property(property="discountJobs", title="discountJobs", description="знижка на роботи", example="237,60"),
         *      @OA\Property(property="discountParts", title="discountParts", description="знижка на товари", example="Пикассо_fe04fb8f-837d-11e8-a705-005056812a5f"),
         *      @OA\Property(property="id", title="id", description="Ідентифікатор історії", example="313,48"),
         *      @OA\Property(property="jobsAmountIncludingVAT", title="jobsAmountIncludingVAT", description="сума робіт з ПДВ", example="1346,40"),
         *      @OA\Property(property="jobsAmountVAT", title="jobsAmountVAT", description="сума ПДВ робіт", example="224,40"),
         *      @OA\Property(property="jobsAmountWithoutVAT", title="jobsAmountWithoutVAT", description="сума робіт без ПДВ", example="1122,00"),
         *      @OA\Property(property="model", title="model", description="модель", example="207"),
         *      @OA\Property(property="number", title="number", description="номер історії", example="ARM0020604"),
         *      @OA\Property(property="partsAmountIncludingVAT", title="partsAmountIncludingVAT", description="сума запчастин з ПДВ", example="1776,36"),
         *      @OA\Property(property="partsAmountVAT", title="partsAmountVAT", description="сума ПДВ запчастин", example="296,06"),
         *      @OA\Property(property="partsAmountWithoutVAT", title="partsAmountWithoutVAT", description="сума запчатин без ПДВ", example="1480,30"),
         *      @OA\Property(property="producer", title="producer", description="виробник авто", example="RENAULT"),
         *      @OA\Property(property="recommendations", title="recommendations", description="рекомендації", example="відсутні"),
         *      @OA\Property(property="repairType", title="repairType", description="тип ремонту", example="Технічне обслуговування"),
         *      @OA\Property(property="stateNumber", title="stateNumber", description="дердавний номер автомобіля", example="AA7198PE"),
         *      @OA\Property(property="mileage", title="mileage", description="пробіг", example="115031"),
         *      @OA\Property(property="parts", title="parts", type="array",  @OA\Items(
         *          @OA\Property(property="name", title="Name", description="назва товару", example="Олива Elf Evolution Full-Tech FE 5W30 208L"),
         *          @OA\Property(property="amountIncludingVAT", title="amountIncludingVAT", description="сума з ПДВ", example="734,83"),
         *          @OA\Property(property="amountWithoutVAT", title="amountWithoutVAT", description="сума без ПДВ", example="612,36"),
         *          @OA\Property(property="price", title="price", description="ціна", example="612,36"),
         *          @OA\Property(property="priceWithVAT", title="priceWithVAT", description="ціна з ПДВ", example="247,00"),
         *          @OA\Property(property="priceWithoutVAT", title="priceWithoutVAT", description="ціна без ПДВ", example="247,00"),
         *          @OA\Property(property="producer", title="producer", description="виробник", example="ELF"),
         *          @OA\Property(property="quantity", title="quantity", description="кількість", example="3,50"),
         *          @OA\Property(property="unit", title="unit", description="одиниця виміру", example="л"),
         *          @OA\Property(property="ref", title="ref", description="католожний номер", example="000434"),
         *          @OA\Property(property="rate", title="rate", description="відсоток знижки", example="15"),
         *      )),
         *      @OA\Property(property="jobs", title="jobs", type="array",  @OA\Items(
         *          @OA\Property(property="name", title="Name", description="назва роботи", example="Заміна фільтра салону"),
         *          @OA\Property(property="amountIncludingVAT", title="amountIncludingVAT", description="сума з ПДВ", example="734,83"),
         *          @OA\Property(property="amountWithoutVAT", title="amountWithoutVAT", description="сума без ПДВ", example="612,36"),
         *          @OA\Property(property="price", title="price", description="ціна", example="612,36"),
         *          @OA\Property(property="priceWithVAT", title="priceWithVAT", description="ціна з ПДВ", example="247,00"),
         *          @OA\Property(property="priceWithoutVAT", title="priceWithoutVAT", description="ціна без ПДВ", example="247,00"),
         *          @OA\Property(property="ref", title="ref", description="католожний номер", example="000434"),
         *          @OA\Property(property="rate", title="rate", description="відсоток знижки", example="15"),
         *      )),
         *      @OA\Property(property="customer", title="customer", type="object",
         *          @OA\Property(property="name", title="name", description="повне ім'я", example="Рильська Тетяна Олександрівна"),
         *          @OA\Property(property="FIO", title="FIO", description="ФІО", example="Рильська Т.О."),
         *          @OA\Property(property="phone", title="phone", description="номер телефону", example="+380939838323"),
         *          @OA\Property(property="email", title="email", description="email", example="example@gmail.con"),
         *          @OA\Property(property="date", title="date", description="дата поручення", example="10.12.2017"),
         *          @OA\Property(property="number", title="number", description="номер поручення", example="БЦ63157"),
         *      ),
         *      @OA\Property(property="dispatcher", title="dispatcher", type="object",
         *          @OA\Property(property="position", title="position", description="посада", example="Консультант з сервісу Рено"),
         *          @OA\Property(property="name", title="name", description="повне ім'я", example="Сімаков Олексій Анатолійович"),
         *          @OA\Property(property="date", title="date", description="дата договору", example="09.01.2015"),
         *          @OA\Property(property="number", title="number", description="номер поручення", example="АП45217"),
         *          @OA\Property(property="FIO", title="FIO", description="ФІО", example="Рильська Т.О."),
         *      ),
         *      @OA\Property(property="organization", title="organization", type="object",
         *          @OA\Property(property="name", title="name", description="ФІО", example="ТОВ Арма Моторс"),
         *          @OA\Property(property="phone", title="phone", description="номер телефону", example="тел. (044) 4902300"),
         *          @OA\Property(property="address", title="address", description="адреса", example="Україна, Київська область, м.Бровари, вул. Оболонська, будинок №72"),
         *      ),
         *      @OA\Property(property="owner", title="owner", type="object",
         *          @OA\Property(property="name", title="name", description="повне ім'я", example="Рильська Тетяна Олександрівна"),
         *          @OA\Property(property="phone", title="phone", description="номер телефону", example="+380939838323"),
         *          @OA\Property(property="address", title="address", description="адрес", example="Світанкова, будинок №5"),
         *          @OA\Property(property="email", title="email", description="email", example="example@gmail.com"),
         *          @OA\Property(property="etc", title="etc", description="ІНН", example=""),
         *          @OA\Property(property="certificate", title="certificate", description="свідоцтво власника", example=""),
         *      ),
         *      @OA\Property(property="payer", title="payer", type="object",
         *          @OA\Property(property="name", title="name", description="повне ім'я", example="Рильська Тетяна Олександрівна"),
         *          @OA\Property(property="date", title="date", description="дата договору", example="13.09.2021"),
         *          @OA\Property(property="contract", title="contract", description="назва договору", example="Замовлення на обслуговування"),
         *          @OA\Property(property="number", title="number", description="номер договору", example="ARM0108925"),
         *      )
         * ))
         */
    }
}


