#!/usr/bin/env bash

WHITE="\e[1;97m"
B_YELLOW="\e[1;33m"
YELLOW="\e[0;33m"
RED="\e[0;31m"
GREEN="\e[0;32m"
COLOR="\e[0m"

# Protect against accidental direct execution of the script
if [ "$3" != "execute-script-from-we-file" ]; then
    echo "Run this script using the we command. For more details, execute:"
    printf '%s'"${YELLOW}we install --help\n${COLOR}"
    exit
fi

MODULE_NAME_ARG=$1
MODULE_VERSION_ARG=$2

case $MODULE_NAME_ARG in
    --help|'')
    USAGE="Wezom CMS module installation utility
Usage:
${GREEN}we install [module]${COLOR}

${YELLOW}module${COLOR} - Module name. Example: \"core\"
         It is not necessary to specify the full git repository name like \"core_module\"

         ${WHITE}Note: ${COLOR} If the git module name has underscores, it will be installed with dashes.
                The \"_module\" suffix will also be omitted.
         ${WHITE}Example: ${COLOR} some_cms_module -> some-cms

         Module version ${WHITE}${MODULE_VERSION_ARG}${COLOR} will be installed.
"
    printf '%s'"$USAGE"
    exit
    ;;
esac

OPTIONAL_SUFFIX="_module"

MODULE_NAME="${MODULE_NAME_ARG%"$OPTIONAL_SUFFIX"}"
MODULE_NAME=${MODULE_NAME//"_"/"-"}

MODULES_ROOT="modules"

mkdir -p "${MODULES_ROOT}"

cd "$MODULES_ROOT" || exit

if [ -d "${MODULE_NAME}" ]; then
    echo "Module ${MODULE_NAME} is already installed. Exiting..."
    exit
fi

GIT_MODULE="${MODULE_NAME}_module"
GIT_MODULE=${GIT_MODULE//"-"/"_"}

# Secure execution of the git clone command
git clone "git@bitbucket.org:wezom/${GIT_MODULE}.git" "${MODULE_NAME}" --single-branch --branch "${MODULE_VERSION_ARG}" || exit

echo ""
printf '%s'"${YELLOW}Unlinking the ${COLOR}${B_YELLOW}${MODULE_NAME}${COLOR}${YELLOW} module from the remote git repository${COLOR}\n"

cd "$MODULE_NAME" || exit

rm -rf .git/

if [ -d ".git" ]; then
    printf '%s'"${RED}Failed to delete the .git folder. Please delete it manually.${COLOR}\n"
else
    printf '%s'"${GREEN}.git folder successfully deleted.${COLOR}\n"
fi

VERSION="^${MODULE_VERSION_ARG}"
PACKAGE="wezom/${MODULE_NAME}"
TEST_NAMESPACE="Wezom\\\\\\${MODULE_NAME^}\\\\\\Tests\\\\\\\\"
TEST_PATH="${MODULES_ROOT}/${MODULE_NAME}/tests/"

printf '%s'"\n${B_YELLOW}==========IMPORTANT!==========${COLOR}\n\n"

echo "Module ${MODULE_NAME} with version ${MODULE_VERSION_ARG} has been cloned from the git repository."
echo ""
echo "Complete the installation by performing the following steps:"
echo ""
printf '%s'"1. Add this test namespace to composer.json in the ${GREEN}autoload-dev.psr-4${COLOR} section:\n"
printf '%s'"${GREEN}\"${TEST_NAMESPACE}\": \"${TEST_PATH}\"${COLOR}\n"

echo "2. Install the dependencies:"
printf '%s'"${GREEN}we composer require ${PACKAGE}:${VERSION}${COLOR}\n"
echo ""
