<?php

namespace App\Models\Saas\Support;

use App\Http\Resources\Files\ImageResource;
use App\ModelFilters\Saas\Support\SupportRequestFilter;
use App\Models\Admins\Admin;
use App\Models\Users\User;
use App\Scopes\Saas\Support\SupportGlobalScope;
use App\Traits\Filterable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class SupportRequest extends Model
{
    use HasFactory;
    use Filterable;

    public const STATUS_NEW = 1;
    public const STATUS_IN_WORK = 2;
    public const STATUS_CLOSED = 3;

    public const STATUSES_DESCRIPTION = [
        self::STATUS_NEW => 'New',
        self::STATUS_IN_WORK => 'In work',
        self::STATUS_CLOSED => 'Closed',
    ];

    public const REMOVE_LABEL = 0;

    public const LABEL_BUG = 1;
    public const LABEL_FEATURE = 2;
    public const LABEL_BILLING = 3;
    public const LABEL_OTHER = 4;

    public const LABELS_DESCRIPTION = [
        self::LABEL_BUG => 'Bug',
        self::LABEL_FEATURE => 'Feature',
        self::LABEL_BILLING => 'Billing',
        self::LABEL_OTHER => 'Other'
    ];

    public const SOURCE_CARRIER = 1;
    public const SOURCE_BROKER = 2;
    public const SOURCE_LANDING = 3;

    public const SOURCES_DESCRIPTION = [
        self::SOURCE_CARRIER => 'Carrier',
        self::SOURCE_BROKER => 'Broker',
        self::SOURCE_LANDING => 'Landing'
    ];

    protected $fillable = [
        'id',
        'user_id',
        'admin_id',
        'user_name',
        'user_email',
        'user_phone',
        'source',
        'subject',
        'status',
        'label',
        'viewed',
        'closing_reason',
        'created_at',
        'updated_at'
    ];

    protected $casts = [
        'user_id' => 'int',
        'admin_id' => 'int',
        'source' => 'int',
        'status' => 'int',
        'label' => 'int',
        'viewed' => 'array'
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::addGlobalScope(new SupportGlobalScope());
    }

    /**
     * @return BelongsTo
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class)->withoutGlobalScopes();
    }

    /**
     * @return BelongsTo
     */
    public function admin(): BelongsTo
    {
        return $this->belongsTo(Admin::class);
    }

    /**
     * @return HasMany
     */
    public function messages(): HasMany
    {
        return $this->hasMany(SupportRequestMessage::class);
    }

    public function question(): Model
    {
        $question = $this->messages()->where('is_question', true)->first();
        if ($question !== null) {
            return $question;
        }
        return $this->messages()->orderBy('id')->limit(1)->first();
    }

    /**
     * @return Model
     */
    public function lastMessage(): ?Model
    {
        return $this->messages()
            ->orderByDesc('id')
            ->first();
    }

    public function modelFilter(): string
    {
        return SupportRequestFilter::class;
    }

    public function getAuthorData(): array
    {
        if ($this->user_id) {
            $role = $this->user->roles->first();
            return [
                'id' => $this->user->id,
                'full_name' => $this->user_name,
                'email' => $this->user_email,
                'phone' => $this->user_phone,
                'photo' => ImageResource::make($this->user->getFirstImage()),
                'role' => [
                    'id' => $role->id,
                    'name' => $role->name,
                ],
                'is_support_employee' => false,
            ];
        }

        return [
            'id' => null,
            'full_name' => $this->user_name,
            'email' => $this->user_email,
            'phone' => $this->user_phone,
            'photo' => null,
            'role' => null,
            'is_support_employee' => false,
        ];
    }

    public function getManagerData(): ?array
    {
        if ($this->admin_id) {
            $role = $this->admin->roles->first();
            return [
                'id' => $this->admin->id,
                'full_name' => $this->admin->full_name,
                'email' => $this->admin->email,
                'phone' => $this->admin->phone,
                'photo' => ImageResource::make($this->admin->getFirstImage()),
                'role' => [
                    'id' => $role->id,
                    'name' => $role->name,
                ],
                'is_support_employee' => true,
            ];
        }

        return null;
    }
}
