<?php

declare(strict_types=1);

namespace Wezom\Core\GraphQL\Directives;

use Illuminate\Contracts\Auth\Access\Gate;
use Illuminate\Contracts\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Nuwave\Lighthouse\Execution\ResolveInfo;
use Nuwave\Lighthouse\Schema\Values\FieldValue;
use Nuwave\Lighthouse\Support\Contracts\FieldResolver;
use Nuwave\Lighthouse\Support\Contracts\GraphQLContext;
use Wezom\Admins\Models\Admin;
use Wezom\Core\Enums\PermissionActionEnum;
use Wezom\Core\Services\AbilityCheckerService;
use Wezom\Core\Services\MediaService;
use Wezom\Core\Utils\ResponseMessageHelper;

class DeleteFileDirective extends BaseDirective implements FieldResolver
{
    protected const ENTITY_ID_FIELD_NAME = 'entityId';
    protected const FILE_IDS_FIELD_NAME = 'fileIds';

    public function __construct(
        protected Gate $gate,
        protected MediaService $mediaService,
        protected AbilityCheckerService $abilityCheckerService
    ) {
        parent::__construct($gate, $this->abilityCheckerService);
    }

    public static function definition(): string
    {
        return /** @lang GraphQL */ <<<'GRAPHQL'

directive @deleteFile(
  """
  Disable permissions model check.
  """
  disablePermissionsCheck: Boolean = false

  """
  The ability to check permissions for.
  Support multiple abilities using || delimiter.
  If empty it will generated by: '{model-table-name}.update'
  """
  ability: String

  """
  Authentication guard name.
  """
  guard: String = "graph_admin"

  """
  Specify the class name of the model to be used for ability check.
  Specify if different from the model.
  """
  abilityModel: String

  """
  The field with the ID ability Model is indicated,
  from which the ID will be obtained for checking the permission.
  """
  abilityFieldName: String = "row_id"

  """
  Specify the class name of the model to use.
  This is only needed when the default model detection does not work.
  """
  model: String
) on FIELD_DEFINITION
GRAPHQL;
    }

    public function resolveField(FieldValue $fieldValue): callable
    {
        $modelClass = $this->getModelClass();

        return function (
            mixed $root,
            array $args,
            GraphQLContext $context,
            ResolveInfo $resolveInfo
        ) use ($modelClass): array {
            $this->authenticate($this->directiveArgValue('guard', Admin::GUARD), $context);
            [
                static::ENTITY_ID_FIELD_NAME => $entityId,
                static::FILE_IDS_FIELD_NAME => $fileIds
            ] = $this->getArguments($resolveInfo, $args);

            $model = $modelClass::query()->findOrFail($entityId);

            $this->checkDirectiveAbility($model, $context->user());

            return ResponseMessageHelper::make()
                ->execute(function () use ($model, $fileIds): void {
                    $this->mediaService->delete($model, $fileIds);
                });
        };
    }

    protected function getArguments(ResolveInfo $resolveInfo, array $args): array
    {
        $this->assertHasIdArgument(self::ENTITY_ID_FIELD_NAME, $args, $resolveInfo);

        $this->assertHasIdListArgument(self::FILE_IDS_FIELD_NAME, $args, $resolveInfo);

        return array_only($args, [self::ENTITY_ID_FIELD_NAME, self::FILE_IDS_FIELD_NAME]);
    }

    private function checkDirectiveAbility(Model $model, ?Authenticatable $user): void
    {
        if ($this->directiveArgValue('disablePermissionsCheck')) {
            return;
        }

        $checkedModel = $model;

        // If need check ability by other model
        if ($abilityModel = $this->directiveArgValue('abilityModel')) {
            $abilityFieldName = $this->directiveArgValue('abilityFieldName', 'row_id');

            $checkedModel = $abilityModel::query()->findOrFail($model->{$abilityFieldName});
        }

        $this->checkAbility(
            $user,
            $checkedModel::class,
            PermissionActionEnum::UPDATE,
            [$checkedModel->getKey()]
        );
    }
}
