<?php

declare(strict_types=1);

namespace Wezom\Core\GraphQL\Directives;

use Exception;
use GraphQL\Type\Definition\Type;
use Nuwave\Lighthouse\Exceptions\DefinitionException;
use Nuwave\Lighthouse\Execution\Arguments\Argument;
use Nuwave\Lighthouse\Execution\ResolveInfo;
use Nuwave\Lighthouse\Schema\Values\FieldValue;
use Nuwave\Lighthouse\Support\Contracts\FieldResolver;
use Nuwave\Lighthouse\Support\Contracts\GraphQLContext;
use Wezom\Admins\Models\Admin;
use Wezom\Core\Enums\PermissionActionEnum;
use Wezom\Core\Utils\ResponseMessageHelper;

class MassViewedDirective extends BaseDirective implements FieldResolver
{
    public static function definition(): string
    {
        return /** @lang GraphQL */ <<<'GRAPHQL'
"""
Update model viewed status (datetime).
"""
directive @massViewed(
  """
  The ability to check permissions for.
  Support multiple abilities using || delimiter.
  If empty it will generated by: '{model-table-name}.view'
  """
  ability: String

  """
  Authentication guard name.
  """
  guard: String = "graph_admin"

  """
  Specify the class name of the model to use.
  This is only needed when the default model detection does not work.
  """
  model: String

  """
  Specify the input argument name with [ID!]!.
  """
  idsInputArgumentName: String = "ids"

  """
  Specify the input argument name with Boolean! flag.
  Used for model field name generation (viewedInputArgumentName . '_at')
  """
  viewedInputArgumentName: String = "viewed"
) on FIELD_DEFINITION
GRAPHQL;
    }

    public function resolveField(FieldValue $fieldValue): callable
    {
        $modelClass = $this->getModelClass();

        return function (
            mixed $root,
            array $args,
            GraphQLContext $context,
            ResolveInfo $resolveInfo
        ) use ($modelClass): array {
            $this->authenticate($this->directiveArgValue('guard', Admin::GUARD), $context);

            return ResponseMessageHelper::make()
                ->execute(function () use ($resolveInfo, $args, $modelClass, $context): void {
                    $ids = $this->getIds($resolveInfo, $args);
                    if (empty($ids)) {
                        throw new Exception();
                    }

                    $fieldName = $this->directiveArgValue('viewedInputArgumentName') ?? 'viewed';

                    $this->assertHasRequiredBooleanArgument($fieldName, $args, $resolveInfo);

                    $this->checkAbility(
                        $context->user(),
                        $modelClass,
                        PermissionActionEnum::VIEW,
                        $ids
                    );

                    $viewed = $args[$fieldName];

                    $models = $this->getModels($modelClass, $ids);
                    $hasCustomSetter = method_exists($models->first(), 'setViewedStatus');
                    foreach ($models as $entity) {
                        if ($hasCustomSetter) {
                            /** @phpstan-ignore-next-line */
                            $entity->setViewedStatus($viewed);
                        } else {
                            $entity->{$fieldName . '_at'} = $viewed ? now() : null;
                        }

                        $entity->save();
                    }
                });
        };
    }

    protected function getIds(ResolveInfo $resolveInfo, array $args): array
    {
        $argumentName = $this->directiveArgValue('idsInputArgumentName') ?? 'ids';

        $this->assertHasIdListArgument($argumentName, $args, $resolveInfo);

        return $args[$argumentName];
    }

    protected function assertHasRequiredBooleanArgument(string $name, array $args, ResolveInfo $resolveInfo): void
    {
        if (!array_key_exists($name, $args)) {
            throw new DefinitionException("Missing required '$name' argument of type Boolean!");
        }

        /** @var Argument $argument */
        $argument = $resolveInfo->argumentSet->arguments[$name];
        if ($argument->namedType()->name !== Type::BOOLEAN || !$argument->namedType()->nonNull) {
            throw new DefinitionException("The '$name' argument must be of type Boolean!");
        }
    }
}
