<?php

declare(strict_types=1);

namespace Wezom\Core\GraphQL\Directives;

use Nuwave\Lighthouse\Execution\ResolveInfo;
use Nuwave\Lighthouse\Schema\Values\FieldValue;
use Nuwave\Lighthouse\Support\Contracts\FieldResolver;
use Nuwave\Lighthouse\Support\Contracts\GraphQLContext;
use Wezom\Admins\Models\Admin;
use Wezom\Core\Enums\PermissionActionEnum;
use Wezom\Core\Events\MassDeleteProcessed;
use Wezom\Core\Utils\ResponseMessageHelper;

class MassDeleteDirective extends BaseDirective implements FieldResolver
{
    public static function definition(): string
    {
        return /** @lang GraphQL */ <<<'GRAPHQL'

directive @massDelete(
  """
  Disable permissions model check.
  """
  disablePermissionsCheck: Boolean = false

  """
  The ability to check permissions for.
  Support multiple abilities using || delimiter.
  If empty it will generated by: '{model-table-name}.delete'
  """
  ability: String

  """
  Authentication guard name.
  """
  guard: String = "graph_admin"

  """
  Specify the class name of the model to use.
  This is only needed when the default model detection does not work.
  """
  model: String

  """
  Specify the input argument name with [ID!]!.
  Default is "ids".
  """
  inputArgumentName: String = "ids"
) on FIELD_DEFINITION
GRAPHQL;
    }

    public function resolveField(FieldValue $fieldValue): callable
    {
        $modelClass = $this->getModelClass();

        return function (
            mixed $root,
            array $args,
            GraphQLContext $context,
            ResolveInfo $resolveInfo
        ) use ($modelClass): array {
            $this->authenticate($this->directiveArgValue('guard', Admin::GUARD), $context);

            return ResponseMessageHelper::make()
                ->execute(function () use ($resolveInfo, $args, $modelClass, $context): void {
                    $ids = $this->getIds($resolveInfo, $args);

                    if (!$this->directiveArgValue('disablePermissionsCheck')) {
                        $this->checkAbility(
                            $context->user(),
                            $modelClass,
                            PermissionActionEnum::DELETE,
                            $ids
                        );
                    }

                    $models = $this->getModels($modelClass, $ids);
                    foreach ($models as $model) {
                        $model->delete();
                    }

                    MassDeleteProcessed::dispatch($modelClass, $ids);
                });
        };
    }

    protected function getIds(ResolveInfo $resolveInfo, array $args): array
    {
        $argumentName = $this->directiveArgValue('inputArgumentName') ?? 'ids';

        $this->assertHasIdListArgument($argumentName, $args, $resolveInfo);

        return $args[$argumentName];
    }
}
