<?php

declare(strict_types=1);

namespace Wezom\Core\GraphQL\Directives;

use Illuminate\Contracts\Auth\Access\Gate;
use Nuwave\Lighthouse\Exceptions\DefinitionException;
use Nuwave\Lighthouse\Execution\Arguments\Argument;
use Nuwave\Lighthouse\Execution\ResolveInfo;
use Nuwave\Lighthouse\Schema\Values\FieldValue;
use Nuwave\Lighthouse\Support\Contracts\FieldResolver;
use Nuwave\Lighthouse\Support\Contracts\GraphQLContext;
use Wezom\Admins\Models\Admin;
use Wezom\Core\Enums\PermissionActionEnum;
use Wezom\Core\Services\AbilityCheckerService;
use Wezom\Core\Services\SortService;
use Wezom\Core\Utils\ResponseMessageHelper;

class UpdateSortDirective extends BaseDirective implements FieldResolver
{
    public function __construct(
        protected Gate $gate,
        protected SortService $sortService,
        protected AbilityCheckerService $abilityCheckerService
    ) {
        parent::__construct($gate, $this->abilityCheckerService);
    }

    public static function definition(): string
    {
        return /** @lang GraphQL */ <<<'GRAPHQL'

directive @updateSort(
  """
  Disable permissions model check.
  """
  disablePermissionsCheck: Boolean = false

  """
  The ability to check permissions for.
  Support multiple abilities using || delimiter.
  If empty it will generated by: '{model-table-name}.update'
  """
  ability: String

  """
  Authentication guard name.
  """
  guard: String = "graph_admin"

  """
  Specify the class name of the model to use.
  This is only needed when the default model detection does not work.
  """
  model: String

  """
  Model field name with sort index.
  """
  fieldName: String = "sort"

  """
  Parent field name for update nested items.
  """
  parentFieldName: String = "parent_id"

  """
  Specify the input argument name with UpdateSortPositionInput.
  Default is "input".
  """
  inputArgumentName: String = "input"
) on FIELD_DEFINITION
GRAPHQL;
    }

    public function resolveField(FieldValue $fieldValue): callable
    {
        $modelClass = $this->getModelClass();

        return function (
            mixed $root,
            array $args,
            GraphQLContext $context,
            ResolveInfo $resolveInfo
        ) use ($modelClass): array {
            $this->authenticate($this->directiveArgValue('guard', Admin::GUARD), $context);

            ['offset' => $offset, 'items' => $items] = $this->getArguments($resolveInfo, $args);

            if (!$this->directiveArgValue('disablePermissionsCheck')) {
                $this->checkAbility(
                    $context->user(),
                    $modelClass,
                    PermissionActionEnum::UPDATE,
                    $this->getRecursiveIds($items)
                );
            }

            $model = new $modelClass();

            $fieldName = $this->directiveArgValue('fieldName', 'sort');
            $parentFieldName = $this->directiveArgValue('parentFieldName', 'parent_id');

            return ResponseMessageHelper::make()
                ->execute(fn () => $this->sortService->saveSort($model, $items, $offset, $fieldName, $parentFieldName));
        };
    }

    protected function getArguments(ResolveInfo $resolveInfo, array $args): array
    {
        $argumentName = $this->directiveArgValue('inputArgumentName') ?? 'input';

        if (!array_key_exists($argumentName, $args)) {
            throw new DefinitionException("Missing required '$argumentName' argument of type UpdateSortPositionInput!");
        }

        /** @var Argument $inputArgument */
        $inputArgument = $resolveInfo->argumentSet->arguments[$argumentName];
        if ($inputArgument->namedType()->name !== 'UpdateSortPositionInput') {
            throw new DefinitionException("The '$argumentName' argument must be of type UpdateSortPositionInput!");
        }

        return $args[$argumentName];
    }

    private function getRecursiveIds($items, array &$result = []): array
    {
        foreach ($items as $item) {
            $result[] = $item['id'];

            if ($item['children'] ?? []) {
                $this->getRecursiveIds($item['children'] ?? [], $result);
            }
        }

        return $result;
    }
}
